trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: pip install pandas
  displayName: 'Install Pandas'

- script: python week5_weekly_report.py
  displayName: 'Run Weekly Low Progress Report'